const ALL_LABELS = {
    '/Adult': ['Adult'],
    '/Arts & Entertainment': ['Arts', 'Entertainment'],
    '/Arts & Entertainment/Celebrities & Entertainment News': ['Arts', 'Entertainment', 'Celebrities', 'News'],
    '/Arts & Entertainment/Comics & Animation': ['Arts', 'Entertainment', 'Comics', 'Animation'],
    '/Arts & Entertainment/Comics & Animation/Anime & Manga': ['Arts', 'Entertainment', 'Comics', 'Anime', 'Animation', 'Manga'],
    '/Arts & Entertainment/Comics & Animation/Cartoons': ['Arts', 'Entertainment', 'Animation', 'Cartoons'],
    '/Arts & Entertainment/Comics & Animation/Comics': ['Arts', 'Entertainment', 'Comics', 'Animation', 'Manga'],
    '/Arts & Entertainment/Entertainment Industry': ['Arts', 'Entertainment', 'Industry'],
    '/Arts & Entertainment/Entertainment Industry/Film & TV Industry': ['Arts', 'Entertainment', 'Industry', 'Film', 'TV'],
    '/Arts & Entertainment/Entertainment Industry/Recording Industry': ['Arts', 'Entertainment', 'Industry', 'Video', 'Recording'],
    '/Arts & Entertainment/Events & Listings': ['Arts', 'Entertainment', 'Events', 'Listings'],
    '/Arts & Entertainment/Events & Listings/Bars, Clubs & Nightlife': ['Arts', 'Entertainment', 'Events', 'Listings', 'Bars', 'Clubs', 'Nightlife'],
    '/Arts & Entertainment/Events & Listings/Concerts & Music Festivals': ['Arts', 'Entertainment', 'Events', 'Listings', 'Concerts', 'Music', 'Festivals'],
    '/Arts & Entertainment/Events & Listings/Expos & Conventions': ['Arts', 'Entertainment', 'Events', 'Listings', 'Expos', 'Conventions'],
    '/Arts & Entertainment/Events & Listings/Film Festivals': ['Arts', 'Entertainment', 'Events', 'Film', 'Festivals'],
    '/Arts & Entertainment/Events & Listings/Movie Listings & Theater Showtimes': ['Arts', 'Entertainment', 'Events', 'Listings', 'Movie', 'Theater', 'Showtimes'],
    '/Arts & Entertainment/Fun & Trivia': ['Arts', 'Entertainment', 'Fun', 'Trivia'],
    '/Arts & Entertainment/Fun & Trivia/Flash-Based Entertainment': ['Arts', 'Entertainment', 'Fun', 'Trivia', 'Flash'],
    '/Arts & Entertainment/Fun & Trivia/Fun Tests & Silly Surveys': ['Arts', 'Entertainment', 'Fun', 'Trivia', 'Surveys'],
    '/Arts & Entertainment/Humor': ['Arts', 'Entertainment', 'Fun', 'Humor'],
    '/Arts & Entertainment/Humor/Funny Pictures & Videos': ['Arts', 'Entertainment', 'Fun', 'Humor', 'Pictures', 'Videos'],
    '/Arts & Entertainment/Humor/Political Humor': ['Arts', 'Entertainment', 'Fun', 'Humor', 'Politics'],
    '/Arts & Entertainment/Movies': ['Arts', 'Entertainment', 'Movies'],
    '/Arts & Entertainment/Music & Audio': ['Arts', 'Entertainment', 'Music', 'Audio'],
    '/Arts & Entertainment/Music & Audio/CD & Audio Shopping': ['Arts', 'Entertainment', 'Music', 'Audio', 'CD', 'Shopping'],
    '/Arts & Entertainment/Music & Audio/Classical Music': ['Arts', 'Entertainment', 'Music', 'Audio', 'Classic'],
    '/Arts & Entertainment/Music & Audio/Country Music': ['Arts', 'Entertainment', 'Music', 'Audio', 'Country'],
    '/Arts & Entertainment/Music & Audio/Dance & Electronic Music': ['Arts', 'Entertainment', 'Music', 'Audio', 'Dance', 'Electronic'],
    '/Arts & Entertainment/Music & Audio/Experimental & Industrial Music': ['Arts', 'Entertainment', 'Music', 'Audio', 'Experimental'],
    '/Arts & Entertainment/Music & Audio/Jazz & Blues': ['Arts', 'Entertainment', 'Music', 'Audio', 'Jazz', 'Blues'],
    '/Arts & Entertainment/Music & Audio/Music Education & Instruction': ['Arts', 'Entertainment', 'Music', 'Audio', 'Education', 'Instruction'],
    '/Arts & Entertainment/Music & Audio/Music Equipment & Technology': ['Arts', 'Entertainment', 'Music', 'Audio', 'Equipment', 'Technology'],
    '/Arts & Entertainment/Music & Audio/Music Reference': ['Arts', 'Entertainment', 'Music', 'Audio', 'Reference'],
    '/Arts & Entertainment/Music & Audio/Music Streams & Downloads': ['Arts', 'Entertainment', 'Music', 'Audio', 'Streams', 'Downloads'],
    '/Arts & Entertainment/Music & Audio/Music Videos': ['Arts', 'Entertainment', 'Music', 'Audio', 'Videos'],
    '/Arts & Entertainment/Music & Audio/Pop Music': ['Arts', 'Entertainment', 'Music', 'Audio', 'Pop'],
    '/Arts & Entertainment/Music & Audio/Radio': ['Arts', 'Entertainment', 'Music', 'Audio', 'Radio'],
    '/Arts & Entertainment/Music & Audio/Religious Music': ['Arts', 'Entertainment', 'Music', 'Audio', 'Religious'],
    '/Arts & Entertainment/Music & Audio/Rock Music': ['Arts', 'Entertainment', 'Music', 'Audio', 'Rock'],
    '/Arts & Entertainment/Music & Audio/Soundtracks': ['Arts', 'Entertainment', 'Music', 'Audio', 'Soundtracks'],
    '/Arts & Entertainment/Music & Audio/Urban & Hip-Hop': ['Arts', 'Entertainment', 'Music', 'Audio', 'hiphop'],
    '/Arts & Entertainment/Music & Audio/World Music': ['Arts', 'Entertainment', 'Music', 'Audio', 'World'],
    '/Arts & Entertainment/Offbeat': ['Arts', 'Entertainment', 'Offbeat'],
    '/Arts & Entertainment/Offbeat/Occult & Paranormal': ['Arts', 'Entertainment', 'Offbeat', 'Occult', 'Paranormal'],
    '/Arts & Entertainment/Online Media': ['Arts', 'Entertainment', 'Online', 'Media'],
    '/Arts & Entertainment/Online Media/Online Image Galleries': ['Arts', 'Entertainment', 'Online', 'Media', 'Image'],
    '/Arts & Entertainment/Performing Arts': ['Arts', 'Entertainment'],
    '/Arts & Entertainment/Performing Arts/Acting & Theater': ['Arts', 'Entertainment', 'Theater'],
    '/Arts & Entertainment/Performing Arts/Circus': ['Arts', 'Entertainment', 'Circus'],
    '/Arts & Entertainment/Performing Arts/Dance': ['Arts', 'Entertainment', 'Dance'],
    '/Arts & Entertainment/Performing Arts/Magic': ['Arts', 'Entertainment', 'Magic'],
    '/Arts & Entertainment/Performing Arts/Opera': ['Arts', 'Entertainment', 'Opera'],
    '/Arts & Entertainment/TV & Video': ['Arts', 'Entertainment', 'TV', 'Video'],
    '/Arts & Entertainment/TV & Video/Online Video': ['Arts', 'Entertainment', 'TV', 'Video', 'Online'],
    '/Arts & Entertainment/TV & Video/TV Commercials': ['Arts', 'Entertainment', 'TV', 'Video', 'Commercials'],
    '/Arts & Entertainment/TV & Video/TV Shows & Programs': ['Arts', 'Entertainment', 'TV', 'Video', 'Shows', 'Programs'],
    '/Arts & Entertainment/Visual Art & Design': ['Arts', 'Entertainment', 'Visual', 'Design'],
    '/Arts & Entertainment/Visual Art & Design/Architecture': ['Arts', 'Entertainment', 'Visual', 'Design', 'Architecture'],
    '/Arts & Entertainment/Visual Art & Design/Art Museums & Galleries': ['Arts', 'Entertainment', 'Visual', 'Design', 'Museums', 'Galleries'],
    '/Arts & Entertainment/Visual Art & Design/Design': ['Arts', 'Entertainment', 'Visual', 'Design'],
    '/Arts & Entertainment/Visual Art & Design/Painting': ['Arts', 'Entertainment', 'Visual', 'Design', 'Painting'],
    '/Arts & Entertainment/Visual Art & Design/Photographic & Digital Arts': ['Arts', 'Entertainment', 'Visual', 'Design', 'Digital', 'Photographic'],
    '/Autos & Vehicles': ['Autos', 'Vehicles'],
    '/Autos & Vehicles/Bicycles & Accessories': ['Autos', 'Vehicles', 'Bicycles'],
    '/Autos & Vehicles/Bicycles & Accessories/Bike Parts & Repair': ['Autos', 'Vehicles', 'Bicycles', 'Parts', 'Repair'],
    '/Autos & Vehicles/Bicycles & Accessories/BMX Bikes': ['Autos', 'Vehicles', 'Bicycles', 'BMX'],
    '/Autos & Vehicles/Boats & Watercraft': ['Autos', 'Vehicles', 'Boats', 'Watercraft'],
    '/Autos & Vehicles/Campers & RVs': ['Autos', 'Vehicles', 'Campers', 'RV'],
    '/Autos & Vehicles/Classic Vehicles': ['Autos', 'Vehicles', 'Classic'],
    '/Autos & Vehicles/Commercial Vehicles/Cargo Trucks & Trailers': ['Autos', 'Vehicles', 'Commercial', 'Trucks', 'Cargo'],
    '/Autos & Vehicles/Motor Vehicles (By Type)': ['Autos', 'Vehicles', 'Motor'],
    '/Autos & Vehicles/Motor Vehicles (By Type)/Hybrid & Alternative Vehicles': ['Autos', 'Vehicles', 'Motor', 'Hybrid'],
    '/Autos & Vehicles/Motor Vehicles (By Type)/Motorcycles': ['Autos', 'Vehicles', 'Motorcycles', 'Motor'],
    '/Autos & Vehicles/Motor Vehicles (By Type)/Off-Road Vehicles': ['Autos', 'Vehicles', 'Motor', 'Off-Road'],
    '/Autos & Vehicles/Motor Vehicles (By Type)/Trucks & SUVs': ['Autos', 'Vehicles', 'Motor', 'Trucks', 'SUV'],
    '/Autos & Vehicles/Vehicle Codes & Driving Laws': ['Autos', 'Vehicles', 'Codes', 'Laws'],
    '/Autos & Vehicles/Vehicle Codes & Driving Laws/Vehicle Licensing & Registration': ['Autos', 'Vehicles', 'Codes', 'Laws', 'Licenses'],
    '/Autos & Vehicles/Vehicle Parts & Services': ['Autos', 'Vehicles', 'Parts', 'Services'],
    '/Autos & Vehicles/Vehicle Parts & Services/Gas Prices & Vehicle Fueling': ['Autos', 'Vehicles', 'Parts', 'Services', 'Gas', 'Fueling'],
    '/Autos & Vehicles/Vehicle Parts & Services/Vehicle Parts & Accessories': ['Autos', 'Vehicles', 'Parts', 'Services'],
    '/Autos & Vehicles/Vehicle Parts & Services/Vehicle Repair & Maintenance': ['Autos', 'Vehicles', 'Parts', 'Services'],
    '/Autos & Vehicles/Vehicle Shopping': ['Autos', 'Vehicles', 'Shopping', 'Services'],
    '/Autos & Vehicles/Vehicle Shopping/Used Vehicles': ['Autos', 'Vehicles', 'Shopping', 'Services', 'Used'],
    '/Autos & Vehicles/Vehicle Shows': ['Autos', 'Vehicles', 'Shopping', 'Services', 'Shows'],
    '/Beauty & Fitness': ['Beauty', 'Fitness'],
    '/Beauty & Fitness/Beauty Pageants': ['Beauty', 'Fitness', 'Pageants'],
    '/Beauty & Fitness/Body Art': ['Beauty', 'Fitness', 'Body', 'Art'],
    '/Beauty & Fitness/Cosmetic Procedures': ['Beauty', 'Fitness', 'Cosmetic', 'Procedures'],
    '/Beauty & Fitness/Cosmetic Procedures/Cosmetic Surgery': ['Beauty', 'Fitness', 'Cosmetic', 'Procedures', 'Surgery'],
    '/Beauty & Fitness/Cosmetology & Beauty Professionals': ['Beauty', 'Fitness', 'Cosmetic', 'Procedures', 'Professionals'],
    '/Beauty & Fitness/Face & Body Care': ['Beauty', 'Fitness', 'Cosmetic', 'Procedures', 'Body', 'Care'],
    '/Beauty & Fitness/Face & Body Care/Hygiene & Toiletries': ['Beauty', 'Fitness', 'Body', 'Care', 'Toiletries', 'Hygiene'],
    '/Beauty & Fitness/Face & Body Care/Make-Up & Cosmetics': ['Beauty', 'Fitness', 'Body', 'Care', 'Cosmetics', 'Makeup'],
    '/Beauty & Fitness/Face & Body Care/Perfumes & Fragrances': ['Beauty', 'Fitness', 'Body', 'Care', 'Cosmetics', 'Makeup'],
    '/Beauty & Fitness/Face & Body Care/Skin & Nail Care': ['Beauty', 'Fitness', 'Body', 'Care', 'Cosmetics', 'Skin', 'Nail'],
    '/Beauty & Fitness/Face & Body Care/Unwanted Body & Facial Hair Removal': ['Beauty', 'Fitness', 'Body', 'Care', 'Cosmetics', 'Removal'],
    '/Beauty & Fitness/Fashion & Style': ['Fashion', 'Fitness', 'Style'],
    '/Beauty & Fitness/Fashion & Style/Fashion Designers & Collections': ['Fashion', 'Fitness', 'Style', 'Designers', 'Collections'],
    '/Beauty & Fitness/Fitness': ['Fashion', 'Fitness', 'Style'],
    '/Beauty & Fitness/Hair Care': ['Fashion', 'Fitness', 'Hair', 'Care'],
    '/Beauty & Fitness/Hair Care/Hair Loss': ['Fashion', 'Fitness', 'Hair', 'Care', 'Loss'],
    '/Beauty & Fitness/Spas & Beauty Services': ['Fashion', 'Fitness', 'Spa', 'Beauty', 'Services'],
    '/Beauty & Fitness/Spas & Beauty Services/Massage Therapy': ['Fashion', 'Fitness', 'Spa', 'Beauty', 'Services'],
    '/Beauty & Fitness/Weight Loss': ['Fashion', 'Fitness', 'Beauty', 'Weight', 'Loss'],
    '/Books & Literature': ['Books', 'Literature'],
    '/Books & Literature/Children\'s Literature': ['Books', 'Literature', 'Children'],
    '/Books & Literature/E-Books': ['Books', 'Literature', 'eBooks'],
    '/Books & Literature/Fan Fiction': ['Books', 'Literature', 'Fiction'],
    '/Books & Literature/Literary Classics': ['Books', 'Literature', 'Classics'],
    '/Books & Literature/Poetry': ['Books', 'Literature', 'Poetry'],
    '/Books & Literature/Writers Resources': ['Books', 'Literature', 'Writers', 'Resources'],
    '/Business & Industrial': ['Business', 'Industrial'],
    '/Business & Industrial/Advertising & Marketing/Public Relations': ['Business', 'Industrial', 'Advertising', 'Marketing', 'Public'],
    '/Business & Industrial/Aerospace & Defense/Space Technology': ['Business', 'Industrial', 'Technology', 'Space', 'Defense'],
    '/Business & Industrial/Agriculture & Forestry': ['Business', 'Industrial', 'Agriculture', 'Forestry'],
    '/Business & Industrial/Agriculture & Forestry/Agricultural Equipment': ['Business', 'Industrial', 'Agriculture', 'Forestry'],
    '/Business & Industrial/Agriculture & Forestry/Forestry': ['Business', 'Industrial', 'Agriculture', 'Forestry'],
    '/Business & Industrial/Agriculture & Forestry/Livestock': ['Business', 'Industrial', 'Agriculture', 'Forestry'],
    '/Business & Industrial/Automotive Industry': ['Business', 'Industrial', 'Automotive'],
    '/Business & Industrial/Business Education': ['Business', 'Industrial', 'Education', 'Business'],
    '/Business & Industrial/Business Finance': ['Business', 'Industrial', 'Finance', 'Business'],
    '/Business & Industrial/Business Finance/Venture Capital': ['Business', 'Industrial', 'Finance', 'Business'],
    '/Business & Industrial/Business Operations': ['Business', 'Industrial', 'Finance', 'Business'],
    '/Business & Industrial/Business Operations/Business Plans & Presentations': ['Business', 'Industrial', 'Finance', 'Business'],
    '/Business & Industrial/Business Operations/Management': ['Business', 'Industrial', 'Management', 'Business'],
    '/Business & Industrial/Business Services': ['Business', 'Industrial', 'Finance', 'Business'],
    '/Business & Industrial/Business Services/Consulting': ['Business', 'Industrial', 'Consulting', 'Business'],
    '/Business & Industrial/Business Services/Corporate Events': ['Business', 'Industrial', 'Events', 'Business'],
    '/Business & Industrial/Business Services/E-Commerce Services': ['Business', 'Industrial', 'Services', 'eCommerce', 'Business'],
    '/Business & Industrial/Business Services/Fire & Security Services': ['Business', 'Industrial', 'Services', 'Security', 'Fire'],
    '/Business & Industrial/Business Services/Office Services': ['Business', 'Industrial', 'Services', 'Office', 'Business'],
    '/Business & Industrial/Business Services/Office Supplies': ['Business', 'Industrial', 'Services', 'Office', 'Business'],
    '/Business & Industrial/Business Services/Writing & Editing Services': ['Business', 'Industrial', 'Services', 'Writing', 'Business'],
    '/Business & Industrial/Chemicals Industry': ['Business', 'Industrial', 'Chemicals'],
    '/Business & Industrial/Chemicals Industry/Cleaning Agents': ['Business', 'Industrial', 'Chemicals', 'Cleaning'],
    '/Business & Industrial/Chemicals Industry/Plastics & Polymers': ['Business', 'Industrial', 'Chemicals', 'Plastics'],
    '/Business & Industrial/Construction & Maintenance': ['Business', 'Industrial', 'Construction'],
    '/Business & Industrial/Construction & Maintenance/Building Materials & Supplies': ['Business', 'Industrial', 'Construction', 'Supplies'],
    '/Business & Industrial/Energy & Utilities': ['Business', 'Industrial', 'Energy', 'Utilities'],
    '/Business & Industrial/Energy & Utilities/Electricity': ['Business', 'Industrial', 'Energy', 'Utilities'],
    '/Business & Industrial/Energy & Utilities/Oil & Gas': ['Business', 'Industrial', 'Energy', 'Utilities', 'Gas'],
    '/Business & Industrial/Energy & Utilities/Renewable & Alternative Energy': ['Business', 'Industrial', 'Energy', 'Utilities'],
    '/Business & Industrial/Hospitality Industry': ['Business', 'Industrial', 'Hospitality'],
    '/Business & Industrial/Hospitality Industry/Event Planning': ['Business', 'Industrial', 'Hospitality', 'Events'],
    '/Business & Industrial/Hospitality Industry/Food Service': ['Business', 'Industrial', 'Hospitality', 'Food'],
    '/Business & Industrial/Industrial Materials & Equipment': ['Business', 'Industrial', 'Materials', 'Equipment'],
    '/Business & Industrial/Industrial Materials & Equipment/Heavy Machinery': ['Business', 'Industrial', 'Materials', 'Equipment'],
    '/Business & Industrial/Manufacturing': ['Business', 'Industrial', 'Materials', 'Manufacturing'],
    '/Business & Industrial/Metals & Mining': ['Business', 'Industrial', 'Materials', 'Metals', 'Mining'],
    '/Business & Industrial/Metals & Mining/Precious Metals': ['Business', 'Industrial', 'Materials', 'Metals', 'Mining'],
    '/Business & Industrial/Pharmaceuticals & Biotech': ['Business', 'Industrial', 'Materials', 'Pharmaceuticals', 'Biotech'],
    '/Business & Industrial/Printing & Publishing': ['Business', 'Industrial', 'Printing', 'Publishing'],
    '/Business & Industrial/Retail Trade': ['Business', 'Industrial', 'Retail', 'Trade'],
    '/Business & Industrial/Retail Trade/Retail Equipment & Technology': ['Business', 'Industrial', 'Retail', 'Equipment'],
    '/Business & Industrial/Small Business/MLM & Business Opportunities': ['Business', 'Industrial', 'MLM', 'Business'],
    '/Business & Industrial/Textiles & Nonwovens': ['Business', 'Industrial', 'Nonwovens', 'Textiles'],
    '/Business & Industrial/Transportation & Logistics': ['Business', 'Industrial', 'Transportation', 'Logistics'],
    '/Business & Industrial/Transportation & Logistics/Freight & Trucking': ['Business', 'Industrial', 'Transportation', 'Freight', 'Trucking'],
    '/Business & Industrial/Transportation & Logistics/Mail & Package Delivery': ['Business', 'Industrial', 'Transportation', 'Mail', 'Package'],
    '/Business & Industrial/Transportation & Logistics/Maritime Transport': ['Business', 'Industrial', 'Transport', 'Maritime'],
    '/Business & Industrial/Transportation & Logistics/Moving & Relocation': ['Business', 'Industrial', 'Moving', 'Relocation'],
    '/Business & Industrial/Transportation & Logistics/Packaging': ['Business', 'Industrial', 'Packaging', 'Logistics'],
    '/Business & Industrial/Transportation & Logistics/Parking': ['Business', 'Industrial', 'Parking', 'Logistics'],
    '/Business & Industrial/Transportation & Logistics/Rail Transport': ['Business', 'Industrial', 'Transport', 'Logistics'],
    '/Business & Industrial/Transportation & Logistics/Urban Transport': ['Business', 'Industrial', 'Transport', 'Logistics'],
    '/Computers & Electronics': ['Electronics', 'Computers'],
    '/Computers & Electronics/CAD & CAM': ['Electronics', 'Computers', 'CAD', 'CAM'],
    '/Computers & Electronics/Computer Hardware': ['Electronics', 'Computers', 'Hardware'],
    '/Computers & Electronics/Computer Hardware/Computer Components': ['Electronics', 'Computers'],
    '/Computers & Electronics/Computer Hardware/Computer Drives & Storage': ['Electronics', 'Computers'],
    '/Computers & Electronics/Computer Hardware/Computer Peripherals': ['Electronics', 'Computers'],
    '/Computers & Electronics/Computer Hardware/Desktop Computers': ['Electronics', 'Computers'],
    '/Computers & Electronics/Computer Hardware/Laptops & Notebooks': ['Electronics', 'Computers'],
    '/Computers & Electronics/Computer Security': ['Electronics', 'Computers', 'Security'],
    '/Computers & Electronics/Computer Security/Hacking & Cracking': ['Electronics', 'Computers', 'Security'],
    '/Computers & Electronics/Consumer Electronics': ['Electronics', 'Computers'],
    '/Computers & Electronics/Consumer Electronics/Audio Equipment': ['Electronics', 'Computers', 'Audio'],
    '/Computers & Electronics/Consumer Electronics/Camera & Photo Equipment': ['Electronics', 'Computers', 'Photo'],
    '/Computers & Electronics/Consumer Electronics/Car Electronics': ['Electronics', 'Computers', 'Car'],
    '/Computers & Electronics/Consumer Electronics/Drones & RC Aircraft': ['Electronics', 'Computers', 'Aircraft'],
    '/Computers & Electronics/Consumer Electronics/Game Systems & Consoles': ['Electronics', 'Computers', 'Consoles'],
    '/Computers & Electronics/Consumer Electronics/GPS & Navigation': ['Electronics', 'Computers', 'Navigation'],
    '/Computers & Electronics/Consumer Electronics/TV & Video Equipment': ['Electronics', 'Computers', 'Video'],
    '/Computers & Electronics/Electronics & Electrical': ['Electronics', 'Computers'],
    '/Computers & Electronics/Electronics & Electrical/Electronic Components': ['Electronics', 'Computers'],
    '/Computers & Electronics/Electronics & Electrical/Power Supplies': ['Electronics', 'Computers'],
    '/Computers & Electronics/Enterprise Technology': ['Electronics', 'Computers'],
    '/Computers & Electronics/Enterprise Technology/Data Management': ['Electronics', 'Computers', 'Data'],
    '/Computers & Electronics/Networking': ['Electronics', 'Computers', 'Networking'],
    '/Computers & Electronics/Networking/Data Formats & Protocols': ['Electronics', 'Computers', 'Networking'],
    '/Computers & Electronics/Networking/Network Monitoring & Management': ['Electronics', 'Computers', 'Networking'],
    '/Computers & Electronics/Networking/VPN & Remote Access': ['Electronics', 'Computers', 'Networking', 'VPN'],
    '/Computers & Electronics/Programming': ['Electronics', 'Computers', 'Programming'],
    '/Computers & Electronics/Programming/Java (Programming Language)': ['Electronics', 'Computers', 'Programming'],
    '/Computers & Electronics/Software': ['Electronics', 'Computers', 'Software'],
    '/Computers & Electronics/Software/Business & Productivity Software': ['Electronics', 'Computers', 'Software'],
    '/Computers & Electronics/Software/Device Drivers': ['Electronics', 'Computers', 'Software'],
    '/Computers & Electronics/Software/Internet Software': ['Electronics', 'Computers', 'Software'],
    '/Computers & Electronics/Software/Multimedia Software': ['Electronics', 'Computers', 'Software'],
    '/Computers & Electronics/Software/Operating Systems': ['Electronics', 'Computers', 'Software'],
    '/Computers & Electronics/Software/Software Utilities': ['Electronics', 'Computers', 'Software'],
    '/Finance': ['Finance'],
    '/Finance/Accounting & Auditing': ['Finance', 'Auditing'],
    '/Finance/Accounting & Auditing/Billing & Invoicing': ['Finance', 'Accounting', 'Invoicing'],
    '/Finance/Accounting & Auditing/Tax Preparation & Planning': ['Finance', 'Accounting', 'Tax'],
    '/Finance/Banking': ['Finance', 'Accounting', 'Banking'],
    '/Finance/Credit & Lending': ['Finance', 'Credit', 'Lending'],
    '/Finance/Credit & Lending/Credit Cards': ['Finance', 'Credit', 'Lending'],
    '/Finance/Credit & Lending/Credit Reporting & Monitoring': ['Finance', 'Credit', 'Lending'],
    '/Finance/Credit & Lending/Loans': ['Finance', 'Credit', 'Lending'],
    '/Finance/Financial Planning & Management': ['Finance', 'Planning', 'Management'],
    '/Finance/Financial Planning & Management/Retirement & Pension': ['Finance', 'Planning', 'Management'],
    '/Finance/Grants, Scholarships & Financial Aid': ['Finance', 'Grants', 'Scholarships'],
    '/Finance/Grants, Scholarships & Financial Aid/Study Grants & Scholarships': ['Finance', 'Grants', 'Scholarships'],
    '/Finance/Insurance': ['Finance', 'Insurance'],
    '/Finance/Insurance/Health Insurance': ['Finance', 'Insurance'],
    '/Finance/Investing': ['Finance', 'Investing'],
    '/Finance/Investing/Commodities & Futures Trading': ['Finance', 'Investing'],
    '/Finance/Investing/Currencies & Foreign Exchange': ['Finance', 'Investing'],
    '/Finance/Investing/Stocks & Bonds': ['Finance', 'Investing'],
    '/Food & Drink': ['Food', 'Drink'],
    '/Food & Drink/Beverages': ['Food', 'Drink'],
    '/Food & Drink/Beverages/Alcoholic Beverages': ['Food', 'Drink', 'Alcohol'],
    '/Food & Drink/Beverages/Coffee & Tea': ['Food', 'Drink', 'Coffee'],
    '/Food & Drink/Beverages/Juice': ['Food', 'Drink'],
    '/Food & Drink/Beverages/Soft Drinks': ['Food', 'Drink'],
    '/Food & Drink/Cooking & Recipes': ['Food', 'Drink', 'Cooking'],
    '/Food & Drink/Cooking & Recipes/BBQ & Grilling': ['Food', 'Drink', 'Cooking'],
    '/Food & Drink/Cooking & Recipes/Desserts': ['Food', 'Drink', 'Cooking'],
    '/Food & Drink/Cooking & Recipes/Soups & Stews': ['Food', 'Drink', 'Cooking'],
    '/Food & Drink/Food': ['Food', 'Drink'],
    '/Food & Drink/Food & Grocery Retailers': ['Food', 'Drink'],
    '/Food & Drink/Food/Baked Goods': ['Food', 'Drink'],
    '/Food & Drink/Food/Breakfast Foods': ['Food', 'Drink'],
    '/Food & Drink/Food/Candy & Sweets': ['Food', 'Drink'],
    '/Food & Drink/Food/Grains & Pasta': ['Food', 'Drink'],
    '/Food & Drink/Food/Meat & Seafood': ['Food', 'Drink'],
    '/Food & Drink/Food/Snack Foods': ['Food', 'Drink'],
    '/Food & Drink/Restaurants': ['Food', 'Drink', 'Restaurants'],
    '/Food & Drink/Restaurants/Fast Food': ['Food', 'Drink', 'Restaurants'],
    '/Food & Drink/Restaurants/Pizzerias': ['Food', 'Drink', 'Restaurants'],
    '/Food & Drink/Restaurants/Restaurant Reviews & Reservations': ['Food', 'Drink', 'Restaurants'],
    '/Games': ['Games'],
    '/Games/Arcade & Coin-Op Games': ['Games'],
    '/Games/Board Games': ['Games', 'Board'],
    '/Games/Board Games/Chess & Abstract Strategy Games': ['Games', 'Board', 'Chess'],
    '/Games/Board Games/Miniatures & Wargaming': ['Games', 'Board'],
    '/Games/Card Games': ['Games', 'Cards'],
    '/Games/Card Games/Collectible Card Games': ['Games', 'Cards'],
    '/Games/Card Games/Poker & Casino Games': ['Games', 'Cards', 'Poker'],
    '/Games/Computer & Video Games': ['Games', 'Computer', 'Video'],
    '/Games/Computer & Video Games/Casual Games': ['Games', 'Computer', 'Video'],
    '/Games/Computer & Video Games/Driving & Racing Games': ['Games', 'Computer', 'Video'],
    '/Games/Computer & Video Games/Fighting Games': ['Games', 'Computer', 'Video'],
    '/Games/Computer & Video Games/Music & Dance Games': ['Games', 'Computer', 'Video'],
    '/Games/Computer & Video Games/Sandbox Games': ['Games', 'Computer', 'Video'],
    '/Games/Computer & Video Games/Shooter Games': ['Games', 'Computer', 'Video'],
    '/Games/Computer & Video Games/Simulation Games': ['Games', 'Computer', 'Video'],
    '/Games/Computer & Video Games/Sports Games': ['Games', 'Computer', 'Video'],
    '/Games/Computer & Video Games/Strategy Games': ['Games', 'Computer', 'Video'],
    '/Games/Computer & Video Games/Video Game Emulation': ['Games', 'Computer', 'Video'],
    '/Games/Family-Oriented Games & Activities': ['Games', 'Computer', 'Video'],
    '/Games/Family-Oriented Games & Activities/Drawing & Coloring': ['Games', 'Computer', 'Video'],
    '/Games/Family-Oriented Games & Activities/Dress-Up & Fashion Games': ['Games', 'Computer', 'Video'],
    '/Games/Gambling': ['Games', 'Gambling'],
    '/Games/Gambling/Lottery': ['Games', 'Gambling'],
    '/Games/Online Games/Massively Multiplayer Games': ['Games', 'Online', 'Multiplayer'],
    '/Games/Puzzles & Brainteasers': ['Games', 'Puzzles'],
    '/Games/Roleplaying Games': ['Games', 'Roleplaying'],
    '/Games/Table Games': ['Games', 'Table'],
    '/Games/Table Games/Billiards': ['Games', 'Table'],
    '/Games/Word Games': ['Games', 'Word'],
    '/Health': ['Health'],
    '/Health/Aging & Geriatrics': ['Health'],
    '/Health/Health Conditions': ['Health'],
    '/Health/Health Conditions/AIDS & HIV': ['Health'],
    '/Health/Health Conditions/Allergies': ['Health'],
    '/Health/Health Conditions/Arthritis': ['Health'],
    '/Health/Health Conditions/Cancer': ['Health'],
    '/Health/Health Conditions/Diabetes': ['Health'],
    '/Health/Health Conditions/Ear Nose & Throat': ['Health'],
    '/Health/Health Conditions/Eating Disorders': ['Health'],
    '/Health/Health Conditions/Endocrine Conditions': ['Health'],
    '/Health/Health Conditions/Genetic Disorders': ['Health'],
    '/Health/Health Conditions/Heart & Hypertension': ['Health'],
    '/Health/Health Conditions/Infectious Diseases': ['Health'],
    '/Health/Health Conditions/Neurological Conditions': ['Health'],
    '/Health/Health Conditions/Obesity': ['Health'],
    '/Health/Health Conditions/Pain Management': ['Health'],
    '/Health/Health Conditions/Respiratory Conditions': ['Health'],
    '/Health/Health Conditions/Skin Conditions': ['Health'],
    '/Health/Health Conditions/Sleep Disorders': ['Health'],
    '/Health/Health Education & Medical Training': ['Health'],
    '/Health/Health Foundations & Medical Research': ['Health'],
    '/Health/Medical Devices & Equipment': ['Health', 'Medical'],
    '/Health/Medical Facilities & Services': ['Health', 'Medical', 'Services'],
    '/Health/Medical Facilities & Services/Doctors\' Offices': ['Health', 'Medical', 'Services'],
    '/Health/Medical Facilities & Services/Hospitals & Treatment Centers': ['Health', 'Medical', 'Services'],
    '/Health/Medical Facilities & Services/Medical Procedures': ['Health', 'Medical', 'Services'],
    '/Health/Medical Facilities & Services/Physical Therapy': ['Health', 'Medical', 'Services'],
    '/Health/Men\'s Health': ['Health', 'Medical', 'Services'],
    '/Health/Mental Health': ['Health', 'Medical', 'Services'],
    '/Health/Mental Health/Anxiety & Stress': ['Health', 'Medical', 'Services'],
    '/Health/Mental Health/Depression': ['Health', 'Medical', 'Services'],
    '/Health/Nursing': ['Health', 'Medical', 'Services'],
    '/Health/Nursing/Assisted Living & Long Term Care': ['Health', 'Medical', 'Services'],
    '/Health/Nutrition': ['Health', 'Medical', 'Nutrition'],
    '/Health/Nutrition/Special & Restricted Diets': ['Health', 'Medical', 'Nutrition'],
    '/Health/Nutrition/Vitamins & Supplements': ['Health', 'Medical', 'Nutrition'],
    '/Health/Oral & Dental Care': ['Health', 'Medical', 'Dental', 'Care'],
    '/Health/Pharmacy': ['Health', 'Medical', 'Pharmacy'],
    '/Health/Pharmacy/Drugs & Medications': ['Health', 'Medical', 'Pharmacy'],
    '/Health/Public Health': ['Health', 'Medical', 'Pharmacy'],
    '/Health/Public Health/Occupational Health & Safety': ['Health', 'Medical', 'Pharmacy'],
    '/Health/Reproductive Health': ['Health', 'Medical', 'Reproductive'],
    '/Health/Substance Abuse': ['Health', 'Medical', 'Substance'],
    '/Health/Substance Abuse/Drug & Alcohol Testing': ['Health', 'Medical', 'Substance', 'Drug'],
    '/Health/Substance Abuse/Drug & Alcohol Treatment': ['Health', 'Medical', 'Substance', 'Drug'],
    '/Health/Substance Abuse/Smoking & Smoking Cessation': ['Health', 'Medical', 'Smoking'],
    '/Health/Substance Abuse/Steroids & Performance-Enhancing Drugs': ['Health', 'Medical', 'Steroids'],
    '/Health/Vision Care': ['Health', 'Medical', 'Vision'],
    '/Health/Vision Care/Eyeglasses & Contacts': ['Health', 'Medical', 'Vision'],
    '/Health/Women\'s Health': ['Health', 'Medical', 'Women'],
    '/Hobbies & Leisure': ['Hobbies', 'Leisure'],
    '/Hobbies & Leisure/Clubs & Organizations': ['Hobbies', 'Leisure'],
    '/Hobbies & Leisure/Clubs & Organizations/Youth Organizations & Resources': ['Hobbies', 'Leisure'],
    '/Hobbies & Leisure/Crafts': ['Hobbies', 'Leisure'],
    '/Hobbies & Leisure/Crafts/Fiber & Textile Arts': ['Hobbies', 'Leisure'],
    '/Hobbies & Leisure/Merit Prizes & Contests': ['Hobbies', 'Leisure'],
    '/Hobbies & Leisure/Outdoors': ['Hobbies', 'Leisure', 'Outdoor'],
    '/Hobbies & Leisure/Outdoors/Fishing': ['Hobbies', 'Leisure', 'Outdoor'],
    '/Hobbies & Leisure/Outdoors/Hiking & Camping': ['Hobbies', 'Leisure', 'Outdoor'],
    '/Hobbies & Leisure/Paintball': ['Hobbies', 'Leisure', 'Outdoor'],
    '/Hobbies & Leisure/Radio Control & Modeling': ['Hobbies', 'Leisure', 'Radio'],
    '/Hobbies & Leisure/Radio Control & Modeling/Model Trains & Railroads': ['Hobbies', 'Leisure', 'Radio'],
    '/Hobbies & Leisure/Special Occasions': ['Hobbies', 'Leisure', 'Occasions'],
    '/Hobbies & Leisure/Special Occasions/Holidays & Seasonal Events': ['Hobbies', 'Leisure', 'Occasions'],
    '/Hobbies & Leisure/Special Occasions/Weddings': ['Hobbies', 'Leisure', 'Occasions'],
    '/Hobbies & Leisure/Water Activities': ['Hobbies', 'Leisure', 'Water'],
    '/Hobbies & Leisure/Water Activities/Boating': ['Hobbies', 'Leisure', 'Water'],
    '/Hobbies & Leisure/Water Activities/Surf & Swim': ['Hobbies', 'Leisure', 'Water'],
    '/Home & Garden': ['Home', 'Garden'],
    '/Home & Garden/Bed & Bath': ['Home', 'Garden'],
    '/Home & Garden/Bed & Bath/Bathroom': ['Home', 'Garden'],
    '/Home & Garden/Domestic Services': ['Home', 'Garden'],
    '/Home & Garden/Domestic Services/Cleaning Services': ['Home', 'Garden'],
    '/Home & Garden/Gardening & Landscaping': ['Home', 'Garden'],
    '/Home & Garden/Home & Interior Decor': ['Home', 'Garden'],
    '/Home & Garden/Home Appliances': ['Home', 'Garden'],
    '/Home & Garden/Home Furnishings': ['Home', 'Garden'],
    '/Home & Garden/Home Furnishings/Curtains & Window Treatments': ['Home', 'Garden'],
    '/Home & Garden/Home Furnishings/Kitchen & Dining Furniture': ['Home', 'Garden'],
    '/Home & Garden/Home Furnishings/Lamps & Lighting': ['Home', 'Garden'],
    '/Home & Garden/Home Furnishings/Living Room Furniture': ['Home', 'Garden'],
    '/Home & Garden/Home Furnishings/Rugs & Carpets': ['Home', 'Garden'],
    '/Home & Garden/Home Improvement': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Home Improvement/Construction & Power Tools': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Home Improvement/Doors & Windows': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Home Improvement/Flooring': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Home Improvement/House Painting & Finishing': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Home Improvement/Plumbing': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Home Safety & Security': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Home Storage & Shelving': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Home Swimming Pools, Saunas & Spas': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/HVAC & Climate Control': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/HVAC & Climate Control/Fireplaces & Stoves': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Kitchen & Dining': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Kitchen & Dining/Cookware & Diningware': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Kitchen & Dining/Major Kitchen Appliances': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Kitchen & Dining/Small Kitchen Appliances': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Laundry': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Laundry/Washers & Dryers': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Nursery & Playroom': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Pest Control': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Yard & Patio': ['Home', 'Garden', 'Improvements'],
    '/Home & Garden/Yard & Patio/Lawn Mowers': ['Home', 'Garden', 'Improvements'],
    '/Internet & Telecom': ['Internet', 'Telecom'],
    '/Internet & Telecom/Communications Equipment': ['Internet', 'Telecom'],
    '/Internet & Telecom/Communications Equipment/Radio Equipment': ['Internet', 'Telecom'],
    '/Internet & Telecom/Email & Messaging': ['Internet', 'Telecom'],
    '/Internet & Telecom/Email & Messaging/Text & Instant Messaging': ['Internet', 'Telecom'],
    '/Internet & Telecom/Email & Messaging/Voice & Video Chat': ['Internet', 'Telecom'],
    '/Internet & Telecom/Mobile & Wireless': ['Internet', 'Telecom'],
    '/Internet & Telecom/Mobile & Wireless/Mobile & Wireless Accessories': ['Internet', 'Telecom'],
    '/Internet & Telecom/Mobile & Wireless/Mobile Apps & Add-Ons': ['Internet', 'Telecom'],
    '/Internet & Telecom/Mobile & Wireless/Mobile Phones': ['Internet', 'Telecom'],
    '/Internet & Telecom/Service Providers': ['Internet', 'Telecom'],
    '/Internet & Telecom/Service Providers/Cable & Satellite Providers': ['Internet', 'Telecom'],
    '/Internet & Telecom/Web Services': ['Internet', 'Telecom'],
    '/Internet & Telecom/Web Services/Affiliate Programs': ['Internet', 'Telecom'],
    '/Internet & Telecom/Web Services/Web Design & Development': ['Internet', 'Telecom'],
    '/Jobs & Education': ['Jobs', 'Education'],
    '/Jobs & Education/Education': ['Jobs', 'Education'],
    '/Jobs & Education/Education/Colleges & Universities': ['Jobs', 'Education'],
    '/Jobs & Education/Education/Distance Learning': ['Jobs', 'Education'],
    '/Jobs & Education/Education/Homeschooling': ['Jobs', 'Education'],
    '/Jobs & Education/Education/Primary & Secondary Schooling (K-12)': ['Jobs', 'Education'],
    '/Jobs & Education/Education/Standardized & Admissions Tests': ['Jobs', 'Education'],
    '/Jobs & Education/Education/Teaching & Classroom Resources': ['Jobs', 'Education'],
    '/Jobs & Education/Education/Training & Certification': ['Jobs', 'Education'],
    '/Jobs & Education/Education/Vocational & Continuing Education': ['Jobs', 'Education'],
    '/Jobs & Education/Jobs': ['Jobs', 'Education'],
    '/Jobs & Education/Jobs/Career Resources & Planning': ['Jobs', 'Education'],
    '/Jobs & Education/Jobs/Job Listings': ['Jobs', 'Education'],
    '/Jobs & Education/Jobs/Resumes & Portfolios': ['Jobs', 'Education'],
    '/Law & Government': ['Law', 'Government'],
    '/Law & Government/Government': ['Law', 'Government'],
    '/Law & Government/Government/Courts & Judiciary': ['Law', 'Government'],
    '/Law & Government/Government/Visa & Immigration': ['Law', 'Government'],
    '/Law & Government/Legal': ['Law', 'Government'],
    '/Law & Government/Legal/Bankruptcy': ['Law', 'Government'],
    '/Law & Government/Legal/Legal Education': ['Law', 'Government'],
    '/Law & Government/Legal/Legal Services': ['Law', 'Government'],
    '/Law & Government/Military': ['Law', 'Government'],
    '/Law & Government/Public Safety': ['Law', 'Government'],
    '/Law & Government/Public Safety/Crime & Justice': ['Law', 'Government'],
    '/Law & Government/Public Safety/Emergency Services': ['Law', 'Government'],
    '/Law & Government/Public Safety/Law Enforcement': ['Law', 'Government'],
    '/Law & Government/Public Safety/Security Products & Services': ['Law', 'Government'],
    '/Law & Government/Social Services': ['Law', 'Government'],
    '/News': ['News'],
    '/News/Business News': ['News'],
    '/News/Business News/Company News': ['News'],
    '/News/Business News/Financial Markets News': ['News'],
    '/News/Gossip & Tabloid News/Scandals & Investigations': ['News'],
    '/News/Health News': ['News'],
    '/News/Politics': ['News'],
    '/News/Sports News': ['News'],
    '/News/Weather': ['News'],
    '/Online Communities': ['Online', 'Communities'],
    '/Online Communities/Blogging Resources & Services': ['Online', 'Communities'],
    '/Online Communities/Dating & Personals': ['Online', 'Communities'],
    '/Online Communities/Dating & Personals/Matrimonial Services': ['Online', 'Communities'],
    '/Online Communities/Dating & Personals/Personals': ['Online', 'Communities'],
    '/Online Communities/Dating & Personals/Photo Rating Sites': ['Online', 'Communities'],
    '/Online Communities/File Sharing & Hosting': ['Online', 'Communities'],
    '/Online Communities/Online Goodies': ['Online', 'Communities'],
    '/Online Communities/Online Goodies/Clip Art & Animated GIFs': ['Online', 'Communities'],
    '/Online Communities/Online Goodies/Skins, Themes & Wallpapers': ['Online', 'Communities'],
    '/Online Communities/Online Goodies/Social Network Apps & Add-Ons': ['Online', 'Communities'],
    '/Online Communities/Photo & Video Sharing': ['Online', 'Communities'],
    '/Online Communities/Photo & Video Sharing/Photo & Image Sharing': ['Online', 'Communities'],
    '/Online Communities/Social Networks': ['Online', 'Communities'],
    '/Online Communities/Virtual Worlds': ['Online', 'Communities'],
    '/People & Society': ['People', 'Society'],
    '/People & Society/Family & Relationships': ['People', 'Society'],
    '/People & Society/Family & Relationships/Family': ['People', 'Society', 'Family'],
    '/People & Society/Family & Relationships/Marriage': ['People', 'Society', 'Family'],
    '/People & Society/Family & Relationships/Troubled Relationships': ['People', 'Society', 'Family'],
    '/People & Society/Kids & Teens': ['People', 'Society', 'Family'],
    '/People & Society/Kids & Teens/Children\'s Interests': ['People', 'Society', 'Family'],
    '/People & Society/Kids & Teens/Teen Interests': ['People', 'Society', 'Family'],
    '/People & Society/Religion & Belief': ['People', 'Society', 'Family'],
    '/People & Society/Seniors & Retirement': ['People', 'Society', 'Family'],
    '/People & Society/Social Issues & Advocacy': ['People', 'Society', 'Family'],
    '/People & Society/Social Issues & Advocacy/Charity & Philanthropy': ['People', 'Society', 'Family'],
    '/People & Society/Social Issues & Advocacy/Discrimination & Identity Relations': ['People', 'Society', 'Family'],
    '/People & Society/Social Issues & Advocacy/Green Living & Environmental Issues': ['People', 'Society', 'Family'],
    '/People & Society/Social Issues & Advocacy/Human Rights & Liberties': ['People', 'Society', 'Family'],
    '/People & Society/Social Issues & Advocacy/Poverty & Hunger': ['People', 'Society', 'Family'],
    '/People & Society/Social Issues & Advocacy/Work & Labor Issues': ['People', 'Society', 'Family'],
    '/People & Society/Social Sciences': ['People', 'Society', 'Family'],
    '/People & Society/Social Sciences/Economics': ['People', 'Society', 'Family'],
    '/People & Society/Social Sciences/Political Science': ['People', 'Society', 'Family'],
    '/People & Society/Social Sciences/Psychology': ['People', 'Society', 'Family'],
    '/People & Society/Subcultures & Niche Interests': ['People', 'Society', 'Family'],
    '/Pets & Animals': ['Pets', 'Animals'],
    '/Pets & Animals/Animal Products & Services/Pet Food & Supplies': ['Pets', 'Animals'],
    '/Pets & Animals/Animal Products & Services/Veterinarians': ['Pets', 'Animals'],
    '/Pets & Animals/Pets': ['Pets', 'Animals'],
    '/Pets & Animals/Pets/Birds': ['Pets', 'Animals'],
    '/Pets & Animals/Pets/Cats': ['Pets', 'Animals'],
    '/Pets & Animals/Pets/Dogs': ['Pets', 'Animals'],
    '/Pets & Animals/Pets/Exotic Pets': ['Pets', 'Animals'],
    '/Pets & Animals/Pets/Fish & Aquaria': ['Pets', 'Animals'],
    '/Pets & Animals/Pets/Horses': ['Pets', 'Animals'],
    '/Pets & Animals/Pets/Rabbits & Rodents': ['Pets', 'Animals'],
    '/Pets & Animals/Pets/Reptiles & Amphibians': ['Pets', 'Animals'],
    '/Pets & Animals/Wildlife': ['Pets', 'Animals'],
    '/Real Estate': ['Estate'],
    '/Real Estate/Real Estate Listings': ['Estate'],
    '/Real Estate/Real Estate Listings/Bank-Owned & Foreclosed Properties': ['Estate'],
    '/Real Estate/Real Estate Listings/Commercial Properties': ['Estate'],
    '/Real Estate/Real Estate Listings/Lots & Land': ['Estate'],
    '/Real Estate/Real Estate Listings/Residential Rentals': ['Estate'],
    '/Real Estate/Real Estate Listings/Residential Sales': ['Estate'],
    '/Real Estate/Real Estate Listings/Timeshares & Vacation Properties': ['Estate'],
    '/Real Estate/Real Estate Services': ['Estate'],
    '/Reference': ['Reference'],
    '/Reference/Directories & Listings': ['Reference'],
    '/Reference/Directories & Listings/Business & Personal Listings': ['Reference'],
    '/Reference/General Reference': ['Reference'],
    '/Reference/General Reference/Biographies & Quotations': ['Reference'],
    '/Reference/General Reference/Calculators & Reference Tools': ['Reference'],
    '/Reference/General Reference/Dictionaries & Encyclopedias': ['Reference'],
    '/Reference/General Reference/Forms Guides & Templates': ['Reference'],
    '/Reference/General Reference/Public Records': ['Reference'],
    '/Reference/General Reference/Time & Calendars': ['Reference'],
    '/Reference/Geographic Reference': ['Reference', 'Geography'],
    '/Reference/Geographic Reference/Maps': ['Reference', 'Geography'],
    '/Reference/Humanities': ['Reference', 'Humanities'],
    '/Reference/Humanities/History': ['Reference', 'Humanities'],
    '/Reference/Humanities/Myth & Folklore': ['Reference', 'Humanities'],
    '/Reference/Humanities/Philosophy': ['Reference', 'Humanities'],
    '/Reference/Language Resources': ['Reference', 'Languages'],
    '/Reference/Language Resources/Foreign Language Resources': ['Reference', 'Languages'],
    '/Reference/Libraries & Museums': ['Reference', 'Libraries'],
    '/Reference/Libraries & Museums/Museums': ['Reference', 'Libraries'],
    '/Science': ['Science'],
    '/Science/Astronomy': ['Science'],
    '/Science/Biological Sciences': ['Science'],
    '/Science/Biological Sciences/Neuroscience': ['Science'],
    '/Science/Chemistry': ['Science'],
    '/Science/Computer Science': ['Science'],
    '/Science/Earth Sciences': ['Science'],
    '/Science/Earth Sciences/Atmospheric Science': ['Science', 'Ecology', 'Earth'],
    '/Science/Earth Sciences/Geology': ['Science', 'Ecology', 'Earth'],
    '/Science/Ecology & Environment': ['Science', 'Ecology', 'Earth'],
    '/Science/Ecology & Environment/Climate Change & Global Warming': ['Science', 'Ecology', 'Earth'],
    '/Science/Engineering & Technology': ['Science', 'Engineering', 'Technology'],
    '/Science/Engineering & Technology/Robotics': ['Science', 'Engineering', 'Technology'],
    '/Science/Mathematics': ['Science', 'Engineering', 'Mathematics'],
    '/Science/Mathematics/Statistics': ['Science', 'Engineering', 'Mathematics'],
    '/Science/Physics': ['Science', 'Engineering', 'Physics'],
    '/Science/Scientific Institutions': ['Science', 'Engineering', 'Institutions'],
    '/Sensitive Subjects': ['Sensitive', 'Subjects'],
    '/Shopping': ['Shopping'],
    '/Shopping/Antiques & Collectibles': ['Shopping'],
    '/Shopping/Apparel': ['Shopping', 'Apparel'],
    '/Shopping/Apparel/Athletic Apparel': ['Shopping', 'Apparel'],
    '/Shopping/Apparel/Casual Apparel': ['Shopping'],
    '/Shopping/Apparel/Children\'s Clothing': ['Shopping', 'Apparel'],
    '/Shopping/Apparel/Clothing Accessories': ['Shopping', 'Apparel'],
    '/Shopping/Apparel/Costumes': ['Shopping', 'Apparel'],
    '/Shopping/Apparel/Eyewear': ['Shopping', 'Apparel'],
    '/Shopping/Apparel/Footwear': ['Shopping', 'Apparel'],
    '/Shopping/Apparel/Formal Wear': ['Shopping', 'Apparel'],
    '/Shopping/Apparel/Headwear': ['Shopping', 'Apparel'],
    '/Shopping/Apparel/Men\'s Clothing': ['Shopping', 'Apparel'],
    '/Shopping/Apparel/Swimwear': ['Shopping', 'Apparel'],
    '/Shopping/Apparel/Undergarments': ['Shopping', 'Apparel'],
    '/Shopping/Apparel/Women\'s Clothing': ['Shopping', 'Apparel'],
    '/Shopping/Auctions': ['Shopping', 'Auctions'],
    '/Shopping/Classifieds': ['Shopping', 'Classifieds'],
    '/Shopping/Consumer Resources': ['Shopping', 'Consumer'],
    '/Shopping/Consumer Resources/Consumer Advocacy & Protection': ['Shopping', 'Consumer'],
    '/Shopping/Consumer Resources/Coupons & Discount Offers': ['Shopping', 'Consumer'],
    '/Shopping/Consumer Resources/Product Reviews & Price Comparisons': ['Shopping', 'Consumer'],
    '/Shopping/Entertainment Media': ['Shopping', 'Entertainment'],
    '/Shopping/Entertainment Media/Entertainment Media Rentals': ['Shopping', 'Entertainment'],
    '/Shopping/Gifts & Special Event Items': ['Shopping', 'Gifts', 'Events'],
    '/Shopping/Gifts & Special Event Items/Cards & Greetings': ['Shopping', 'Gifts', 'Events'],
    '/Shopping/Gifts & Special Event Items/Flowers': ['Shopping', 'Gifts', 'Events'],
    '/Shopping/Gifts & Special Event Items/Gifts': ['Shopping', 'Gifts', 'Events'],
    '/Shopping/Luxury Goods': ['Shopping', 'Goods', 'Luxury'],
    '/Shopping/Mass Merchants & Department Stores': ['Shopping', 'Stores', 'Merchants'],
    '/Shopping/Photo & Video Services': ['Shopping', 'Photo', 'Video'],
    '/Shopping/Tobacco Products': ['Shopping', 'Tobacco', 'Products'],
    '/Shopping/Toys': ['Shopping', 'Toys'],
    '/Shopping/Toys/Building Toys': ['Shopping', 'Toys'],
    '/Shopping/Toys/Die-cast & Toy Vehicles': ['Shopping', 'Toys'],
    '/Shopping/Toys/Dolls & Accessories': ['Shopping', 'Toys'],
    '/Shopping/Toys/Ride-On Toys & Wagons': ['Shopping', 'Toys'],
    '/Shopping/Toys/Stuffed Toys': ['Shopping', 'Toys'],
    '/Sports': ['Sports'],
    '/Sports/Animal Sports': ['Sports'],
    '/Sports/College Sports': ['Sports'],
    '/Sports/Combat Sports': ['Sports'],
    '/Sports/Combat Sports/Boxing': ['Sports'],
    '/Sports/Combat Sports/Martial Arts': ['Sports'],
    '/Sports/Combat Sports/Wrestling': ['Sports'],
    '/Sports/Extreme Sports': ['Sports'],
    '/Sports/Extreme Sports/Drag & Street Racing': ['Sports'],
    '/Sports/Fantasy Sports': ['Sports'],
    '/Sports/Individual Sports': ['Sports'],
    '/Sports/Individual Sports/Cycling': ['Sports'],
    '/Sports/Individual Sports/Golf': ['Sports'],
    '/Sports/Individual Sports/Gymnastics': ['Sports'],
    '/Sports/Individual Sports/Racquet Sports': ['Sports'],
    '/Sports/Individual Sports/Skate Sports': ['Sports'],
    '/Sports/Individual Sports/Track & Field': ['Sports'],
    '/Sports/International Sports Competitions': ['Sports'],
    '/Sports/International Sports Competitions/Olympics': ['Sports'],
    '/Sports/Motor Sports': ['Sports'],
    '/Sports/Sporting Goods': ['Sports'],
    '/Sports/Sporting Goods/Sports Memorabilia': ['Sports'],
    '/Sports/Sporting Goods/Winter Sports Equipment': ['Sports'],
    '/Sports/Sports Coaching & Training': ['Sports'],
    '/Sports/Team Sports': ['Sports', 'Team'],
    '/Sports/Team Sports/American Football': ['Sports', 'Team'],
    '/Sports/Team Sports/Australian Football': ['Sports', 'Team'],
    '/Sports/Team Sports/Baseball': ['Sports', 'Team'],
    '/Sports/Team Sports/Basketball': ['Sports', 'Team'],
    '/Sports/Team Sports/Cheerleading': ['Sports', 'Team'],
    '/Sports/Team Sports/Cricket': ['Sports', 'Team'],
    '/Sports/Team Sports/Hockey': ['Sports', 'Team'],
    '/Sports/Team Sports/Rugby': ['Sports', 'Team'],
    '/Sports/Team Sports/Soccer': ['Sports', 'Team'],
    '/Sports/Team Sports/Volleyball': ['Sports', 'Team'],
    '/Sports/Water Sports': ['Sports', 'Water'],
    '/Sports/Water Sports/Surfing': ['Sports', 'Water'],
    '/Sports/Water Sports/Swimming': ['Sports', 'Water'],
    '/Sports/Winter Sports': ['Sports', 'Winter'],
    '/Sports/Winter Sports/Ice Skating': ['Sports', 'Winter'],
    '/Sports/Winter Sports/Skiing & Snowboarding': ['Sports', 'Winter'],
    '/Travel': ['Travel'],
    '/Travel/Air Travel': ['Travel', 'Air'],
    '/Travel/Air Travel/Airport Parking & Transportation': ['Travel', 'Air'],
    '/Travel/Bus & Rail': ['Travel', 'Bus'],
    '/Travel/Car Rental & Taxi Services': ['Travel', 'Taxi'],
    '/Travel/Cruises & Charters': ['Travel', 'Cruises'],
    '/Travel/Hotels & Accommodations': ['Travel', 'Hotels'],
    '/Travel/Hotels & Accommodations/Vacation Rentals & Short-Term Stays': ['Travel', 'Hotels'],
    '/Travel/Specialty Travel': ['Travel'],
    '/Travel/Tourist Destinations': ['Travel', 'Tourism'],
    '/Travel/Tourist Destinations/Beaches & Islands': ['Travel', 'Tourism'],
    '/Travel/Tourist Destinations/Mountain & Ski Resorts': ['Travel', 'Tourism'],
    '/Travel/Tourist Destinations/Regional Parks & Gardens': ['Travel', 'Tourism'],
    '/Travel/Tourist Destinations/Theme Parks': ['Travel', 'Tourism'],
    '/Travel/Tourist Destinations/Zoos-Aquariums-Preserves': ['Travel', 'Tourism']
};

export default ALL_LABELS;
